## 形状
> [Array manipulation routines](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)
>

`ndarray`的形状由沿每个轴的元素数量决定，通过`ndim`、`shape`、`size`属性可以获取数组的轴数、形状和元素总数。

`numpy`包中也提供了函数可以获取数组的轴数、形状和元素总数：

|Routine                  |Desc                                                           |
|-------------------------|---------------------------------------------------------------|
|`np.ndim(a)`             |返回给定`ndarray`的维数（轴数），等同于`a.ndim`|
|`np.shape(a)`            |返回给定`ndarray`的形状，等同于`a.shape`|
|`np.size(a[,axis=None])` |返回给定`ndarray`的元素总数，等同于`a.size`；如果指定了`axis`则返回给定轴的元素数量，等同与`a.shape[axis]`|

In [1]:
import numpy as np

In [104]:
rng = np.random.default_rng(42)
a = np.floor(rng.normal(size=(3, 4)) * 10) # create a ndarray by normal(loc=0.0, scale=1.0)
print(f"initialized ndarray is \n{a}")
print("------------------------------------------------------------------------------------------------")
print(f"a.ndim:  {a.ndim}      --|-- np.ndim(a):  {np.ndim(a)}")
print(f"a.shape: {a.shape} --|-- np.shape(a): {np.shape(a)}")
print(f"a.size:  {a.size}     --|-- np.size(a):  {np.size(a)}")
print("------------------------------------------------------------------------------------------------")
for axis in range(a.ndim):
    print(f"np.size(a, axis={axis}): {np.size(a, axis=axis)}")

initialized ndarray is 
[[  3. -11.   7.   9.]
 [-20. -14.   1.  -4.]
 [ -1.  -9.   8.   7.]]
------------------------------------------------------------------------------------------------
a.ndim:  2      --|-- np.ndim(a):  2
a.shape: (3, 4) --|-- np.shape(a): (3, 4)
a.size:  12     --|-- np.size(a):  12
------------------------------------------------------------------------------------------------
np.size(a, axis=0): 3
np.size(a, axis=1): 4


### 改变形状

`a`是一个`ndarray`对象，可以通过一下三种方式改变`a`的形状

- `a.shape = (d0, d1, ...)`
- `a = a.reshape(shape)`: 修改`ndarray`的形状，并返回`ndarray`的**视图**
- `a = np.reshape(a, shape)`: 修改`ndarray`的形状，并返回`ndarray`的**视图**，等同于`a = a.reshape(shape)`


In [134]:
rng = np.random.default_rng(42)
a = np.floor(rng.normal(size=(3, 4)) * 10) # create a ndarray by normal(loc=0.0, scale=1.0)
print(f"initialized ndarray 'shape={a.shape}' is:\n{a}")
a1, a2, a3 = a.copy(), a.copy(), a.copy() # deep copy
print("-" * 30, ">>a.shape=()<<", "-" * 30, "\n")
a1.shape = (2, 6)
print(f"use `a.shape=(2, 6)` change ndarray'shape, the origin ndarray updated to:\n{a1}\n")
print("-" * 30, ">>a = a.reshape(shape)<<", "-" * 30, "\n")
new_a2 = a2.reshape(2, 6)
print(f"use `new_a = a.reshape()` change ndarray's shape, origin ndarray is:\n{a2}")
print(f"use `new_a = a.reshape()` change ndarray's shape, new ndarray is:\n{new_a2}")
print(f"new ndarray is a view of origin ndarray? --> {new_a2.base is not None}")
new_a2[0, 0] = 99
print(f"use new ndarray update index [0, 0] to `99`, then origin index [0, 0] is updated to: {a2[0, 0]}\n")
print("-" * 30, ">>a = np.reshape(a, shape)<<", "-" * 30, "\n")
new_a3 = np.reshape(a3, (2, 2, 3))
print(f"use `new_a = np.reshape(a)` change ndarray's shape, origin ndarray is:\n{a3}")
print(f"use `new_a = np.reshape(a)` change ndarray's shape, new ndarray is:\n{new_a3}")
print(f"new ndarray is a view of origin ndarray? --> {new_a3.base is not None}")
new_a3[0, 0] = 99
print(f"use new ndarray update index [0, 0] to `99`, then origin index [0, 0] is updated to: {a3[0, 0]}\n")

initialized ndarray 'shape=(3, 4)' is:
[[  3. -11.   7.   9.]
 [-20. -14.   1.  -4.]
 [ -1.  -9.   8.   7.]]
------------------------------ >>a.shape=()<< ------------------------------ 

use `a.shape=(2, 6)` change ndarray'shape, the origin ndarray updated to:
[[  3. -11.   7.   9. -20. -14.]
 [  1.  -4.  -1.  -9.   8.   7.]]

------------------------------ >>a = a.reshape(shape)<< ------------------------------ 

use `new_a = a.reshape()` change ndarray's shape, origin ndarray is:
[[  3. -11.   7.   9.]
 [-20. -14.   1.  -4.]
 [ -1.  -9.   8.   7.]]
use `new_a = a.reshape()` change ndarray's shape, new ndarray is:
[[  3. -11.   7.   9. -20. -14.]
 [  1.  -4.  -1.  -9.   8.   7.]]
new ndarray is a view of origin ndarray? --> True
use new ndarray update index [0, 0] to `99`, then origin index [0, 0] is updated to: 99.0

------------------------------ >>a = np.reshape(a, shape)<< ------------------------------ 

use `new_a = np.reshape(a)` change ndarray's shape, origin ndarray is:
[[  

### 扁平化

`a`是一个`ndarray`对象，可以通过一下三种方式将`a`折叠为 1D 数组

- `a.flat`: `ndarray`的`flat`属性，返回数组的 1D 迭代器
- `a.flatten()`: 返回折叠为 1D 的`ndarray`的**副本**
- `np.ravel(a)`: 返回折叠为 1D 的`ndarray`的**视图**

In [150]:
rng = np.random.default_rng(42)
a = np.floor(rng.normal(size=(3, 4)) * 10) # create a ndarray by normal(loc=0.0, scale=1.0)
print(f"initialized ndarray 'shape={a.shape}' is:\n{a}")
print(f"flat ndarray as 1D: {list(a.flat)}")
print("-" * 100)
print(", ".join(str(item) for item in a.flat)) 
print("-" * 100)
a1, a2 = a.copy(), a.copy()
a_flat_copy = a1.flatten() # copy
print(f"flat ndarray by ndarray.flatten(), origin ndarray is:\n{a1}")
print(f"flat ndarray by ndarray.flatten(), flated ndarray is:\n{a_flat_copy}")
a_flat_copy *= 2
print("-"*20, "!!!times flated ndarray twice!!!", "-"*20)
print(f"flat ndarray by ndarray.flatten(), origin ndarray is:\n{a1}")
print(f"flat ndarray by ndarray.flatten(), flated ndarray is:\n{a_flat_copy}")
print("-" * 100)
a_revel_view = np.ravel(a2) # view
print(f"flat ndarray by np.ravel(), origin ndarray is:\n{a2}")
print(f"flat ndarray by np.ravel(), flated ndarray is:\n{a_revel_view}")
a_revel_view *= 2
print("-"*20, "!!!times flated ndarray twice!!!", "-"*20)
print(f"flat ndarray by np.ravel(), origin ndarray is:\n{a2}")
print(f"flat ndarray by np.ravel(), flated ndarray is:\n{a_revel_view}")

initialized ndarray 'shape=(3, 4)' is:
[[  3. -11.   7.   9.]
 [-20. -14.   1.  -4.]
 [ -1.  -9.   8.   7.]]
flat ndarray as 1D: [np.float64(3.0), np.float64(-11.0), np.float64(7.0), np.float64(9.0), np.float64(-20.0), np.float64(-14.0), np.float64(1.0), np.float64(-4.0), np.float64(-1.0), np.float64(-9.0), np.float64(8.0), np.float64(7.0)]
----------------------------------------------------------------------------------------------------
3.0, -11.0, 7.0, 9.0, -20.0, -14.0, 1.0, -4.0, -1.0, -9.0, 8.0, 7.0
----------------------------------------------------------------------------------------------------
flat ndarray by ndarray.flatten(), origin ndarray is:
[[  3. -11.   7.   9.]
 [-20. -14.   1.  -4.]
 [ -1.  -9.   8.   7.]]
flat ndarray by ndarray.flatten(), flated ndarray is:
[  3. -11.   7.   9. -20. -14.   1.  -4.  -1.  -9.   8.   7.]
-------------------- !!!times flated ndarray twice!!! --------------------
flat ndarray by ndarray.flatten(), origin ndarray is:
[[  3. -11.   7.  