
|API|Desc|
|---|----|
|`np.concatenate()`|沿现有轴连接一系列数组|
|`np.concat()`|同 `np.concatenate()`|
|`np.stack()` |沿新轴连接一系列数组|



In [1]:
import numpy as np

In [10]:
# np.concatenate(), np.concat()
a = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
b = np.array([[7, 8, 9]]) # (1, 3)
c = np.array([[10], [11]]) # (2, 1)
print(np.concat((a, b), axis=0)) # (3, 3)
print(np.concat((a, c), axis=1)) # (2, 3) concatenate (2, 1) -> (2, 4)
print(np.concat((a, b), axis=None)) # a -> (6, ), b -> (3, ) --> (9, )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 11]]
[1 2 3 4 5 6 7 8 9]


In [33]:
# np.stack
a = np.array([1, 2, 3]) # (3, )
b = np.array([4, 5, 6]) # (3, )
c = np.stack((a, b), axis=0) # (2, 3) --> c[0, :] = a, c[1, :] = b
print(c)
print(c[0, :], c[1, :])
print("-" * 100)
d = np.stack((a, b), axis=1) # (3, 2) --> c[:, 0] = a, c[:, 1] = b
print(d)
print(d[:, 0], d[:, 1])

[[1 2 3]
 [4 5 6]]
[1 2 3] [4 5 6]
----------------------------------------------------------------------------------------------------
[[1 4]
 [2 5]
 [3 6]]
[1 2 3] [4 5 6]


In [35]:
# np.stack()
a = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
b = np.array([[7, 8, 9], [4, 5, 6]]) # (2, 3)
c = np.stack((a, b), axis=0) # (*2*, 2, 3), c[0] = a, c[1] = b 沿着深度堆叠
print(c)
print("-" * 50)
print(c[0])
print("-" * 50)
print(c[1])
print("-" * 100)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [4 5 6]]]
--------------------------------------------------
[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[[7 8 9]
 [4 5 6]]
----------------------------------------------------------------------------------------------------


In [38]:
# np.stack()
a = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
b = np.array([[7, 8, 9], [10, 11, 12]]) # (2, 3)
c = np.stack((a, b), axis=1) # (2, *2*, 3), c[:, 0, :] = a, c[:, 1, :] = b, 这就像把两个矩阵的第一行和第二行分别配对组合。
print(c)
print("-" * 50)
print(c[:, 0, :])
print("-" * 100)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
--------------------------------------------------
[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------


In [40]:
# np.stack()
a = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
b = np.array([[7, 8, 9], [10, 11, 12]]) # (2, 3)
c = np.stack((a, b), axis=-1) # (2, 3, *2*), c[:, :, 0] = a, c[:, :, 1] = b, 这就像把两个矩阵的第一列和第二列分别配对组合。
print(c)
print("-" * 50)
print(c[:, :, 0])
print("-" * 100)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
--------------------------------------------------
[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------


array([[1, 7],
       [2, 8],
       [3, 9]])